### ISSUE TITLE
Unable to run the server.js

### ISSUE THREAD

**Issue by santhosh-vin10** [MicrosoftDocs/mslearn-copilot-plugins#1]
Following this for testing an open AI plugin  MS documentation: 
https://learn.microsoft.com/en-us/copilot-plugins/get-started
 referred  https://github.com/MicrosoftDocs/mslearn-copilot-plugins/tree/main/contoso-real-estate for cloning the code. 
After cloning, following Readme , installed modules, and then trying to run the 
Get this error on node server.js 

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for C:\Users\vinjamos\OneDrive - Jabil\Desktop\Copilot\plugin samples\M365 OpenAIAPI\mslearn-copilot-plugins\contoso-real-estate\listings.json    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Tried  node --experimental-json-modules server.js but just get a warning but doesn't execute.

**Comment by santhosh-vin10** [comment]
Closing it , because it seems like the localhost:8080 actually is running even with the error and I do get response when hitting something like http://localhost:8080/get-listings?city=Atlanta.

**Comment by captainbrosset** [comment]
That's odd. I don't understand where this error could be coming from.
Good to know that it's working anyway. But it would be good to fix the error still. When does it occur exactly? Right when you start the server with `node server.js`? Or later when you access the API via your browser?
What version of Node.JS are you using?

**Comment by santhosh-vin10** [comment]
It happens on node server.js .. when I run the node --experimental-json-modules server.js  , I get a warning 
node:51172) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

I updated my node version to latest and now I don't have to pass the -experimental-json-modules and just use node server.js . it runs but i still see the warning 
 ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by captainbrosset** [comment]
Oh I see. This warning occurs because of this line of code:

`import listings from "./listings.json" assert { type: "json" };`

This makes it possible to read JSON data without having to first fetch it and parse it. Instead, you can just import it like any other module, but with the addition of the `assert` statement.

This syntax is relatively new, and NodeJS prints a warning for people to know that it's still experimental.
That said, it's already at the [stage 3](https://tc39.es/proposal-json-modules/) of the [TC39 process](https://tc39.es/process-document/), which means that the spec is complete and signed off. I think it's fairly safe to use, especially in a demo repo like this one, where we can always change it to something else, should the spec change.
